spool batch1.lst;

DROP TABLE STUDENT_ATT CASCADE CONSTRAINT;
DROP TABLE STUDENT_CLASSENR CASCADE CONSTRAINT;
DROP TABLE FACULTY_ENR CASCADE CONSTRAINT;
DROP TABLE WRITE_TEST CASCADE CONSTRAINT;
DROP TABLE TEST_NO CASCADE CONSTRAINT;
DROP TABLE TEST_ID CASCADE CONSTRAINT;
DROP TABLE SUBJECT_LIST CASCADE CONSTRAINT;
DROP TABLE STUDENT_SEMENR CASCADE CONSTRAINT;
DROP TABLE STUDENT_LIST CASCADE CONSTRAINT;
DROP TABLE CLASS_TCHR CASCADE CONSTRAINT;
DROP TABLE FACULTY_RESPONSIBILITY CASCADE CONSTRAINT;
DROP TABLE FACULTY_LIST CASCADE CONSTRAINT;
DROP TABLE CAMS_LOGIN CASCADE CONSTRAINT;

CREATE TABLE CAMS_LOGIN(
  USERID VARCHAR2(10),
  PASSWORD VARCHAR2(10),
  CONSTRAINT CAMS_LOGIN_PRIME PRIMARY KEY (USERID) ENABLE
);

CREATE TABLE FACULTY_LIST(
  FID VARCHAR2(7),
  NAME VARCHAR2(30) NOT NULL,
  DESIGNATION VARCHAR2(30) NOT NULL,
  BRANCH VARCHAR2(2),
  CONSTRAINT FACULTY_LIST_PRIME PRIMARY KEY (FID),
  CONSTRAINT FACULTY_LIST_FOREIGN FOREIGN KEY (FID) REFERENCES CAMS_LOGIN (USERID) ENABLE
);

CREATE TABLE FACULTY_RESPONSIBILITY(
  FID VARCHAR2(7),
  RESPONSIBILITY VARCHAR2(10),
  CONSTRAINT FACULTY_RESPONSIBILITY_PRIME PRIMARY KEY (FID,RESPONSIBILITY) ENABLE,
  CONSTRAINT FACULTY_RESPONSIBILITY_FOREIGN FOREIGN KEY (FID) REFERENCES FACULTY_LIST (FID) ENABLE
);

CREATE TABLE CLASS_TCHR(
  FID VARCHAR2(7),
  SECTION VARCHAR2(1) NOT NULL,
  SEM NUMBER(1),
  YEAR NUMBER(4),
  CONSTRAINT CLASS_TCHR_PRIME PRIMARY KEY (FID,SEM,YEAR) ENABLE,
  CONSTRAINT CLASS_TCHR_CHECK_SEM CHECK (SEM BETWEEN 1 AND 8) ENABLE,
  CONSTRAINT CLASS_TCHR_FOREIGN_FID FOREIGN KEY (FID) REFERENCES FACULTY_LIST (FID) ENABLE
);

CREATE TABLE STUDENT_LIST(
  USN VARCHAR2(10),
  NAME VARCHAR2(30) NOT NULL,
  JOINING DATE NOT NULL,
  ADDRESS VARCHAR2(300),
  PHNO VARCHAR2(15) NOT NULL,
  PARENT_PHNO VARCHAR2(15) NOT NULL,
  CONSTRAINT STUDENT_LIST_PRIME PRIMARY KEY (USN) ENABLE,
  CONSTRAINT STUDENT_LIST_FOREIGN FOREIGN KEY (USN) REFERENCES CAMS_LOGIN (USERID) ENABLE
);

CREATE TABLE STUDENT_SEMENR(
  USN VARCHAR2(10),
  BRANCH VARCHAR2(2) NOT NULL,
  SEM NUMBER(1) CONSTRAINT STUDENT_SEMENR_CHECK_SEM CHECK (SEM BETWEEN 1 AND 8) ENABLE,
  SECTION VARCHAR2(1),
  MENTORID VARCHAR2(7),
  CONSTRAINT STUDENT_SEMENR_PRIME PRIMARY KEY (USN,SEM,SECTION) ENABLE,
  CONSTRAINT STUDENT_SEMENR_FOREIGN_USN FOREIGN KEY (USN) REFERENCES STUDENT_LIST (USN) ENABLE,
  CONSTRAINT STUDENT_SEMENR_FOREIGN_MENTOR FOREIGN KEY (MENTORID) REFERENCES FACULTY_LIST (FID) ENABLE
);

CREATE TABLE SUBJECT_LIST(
  SCODE VARCHAR2(8),
  SNAME VARCHAR2(100) NOT NULL,
  BRANCH VARCHAR2(2),
  CONSTRAINT SUBJECT_LIST_PRIME PRIMARY KEY (SCODE,BRANCH) ENABLE
);

CREATE TABLE TEST_ID(
  TID VARCHAR2(9),
  YEAR NUMBER(4) NOT NULL,
  SLOT VARCHAR2(1) NOT NULL,
  BRANCH VARCHAR2(2) NOT NULL,
  SEM VARCHAR2(1) CONSTRAINT TEST_ID_CHECK_SEM CHECK (SEM = 'O' OR SEM = 'E') ENABLE,
  TNO NUMBER(1) CONSTRAINT TEST_ID_CHECK_TNO CHECK (TNO BETWEEN 1 AND 3) ENABLE,
  CONSTRAINT TEST_ID_PRIME PRIMARY KEY (TID) ENABLE
);

CREATE TABLE TEST_NO(
  TID VARCHAR2(9),
  SCODE VARCHAR2(8) NOT NULL,
  CONSTRAINT TEST_NO_PRIME PRIMARY KEY (TID) ENABLE,
  CONSTRAINT TEST_NO_FOREIGN_TID FOREIGN KEY (TID) REFERENCES TEST_ID (TID) ENABLE
);

CREATE TABLE WRITE_TEST(
  USN VARCHAR2(10),
  TID VARCHAR2(9),
  SCORE NUMBER(2) CONSTRAINT WRITE_TEST_CHECK_SCORE CHECK (SCORE BETWEEN 0 AND 25) ENABLE,
  CONSTRAINT WRITE_TEST_PRIME PRIMARY KEY (USN,TID) ENABLE,
  CONSTRAINT WRITE_TEST_FOREIGN_USN FOREIGN KEY (USN) REFERENCES STUDENT_LIST (USN) ENABLE,
  CONSTRAINT WRITE_TEST_FOREIGN_TID FOREIGN KEY (TID) REFERENCES TEST_NO (TID) ENABLE
);

CREATE TABLE FACULTY_ENR(
  ENO NUMBER,
  FID VARCHAR2(7) NOT NULL,
  SLOT NUMBER(1) NOT NULL,
  DAY VARCHAR2(3) NOT NULL,
  SECTION VARCHAR2(1) NOT NULL,
  YEAR NUMBER(4) NOT NULL,
  SEM NUMBER(1) NOT NULL,
  CONSTRAINT FACULTY_ENR_PRIME PRIMARY KEY (ENO) ENABLE,
  CONSTRAINT FACULTY_ENR_CHECK_SLOT CHECK (SLOT BETWEEN 1 AND 7) ENABLE,
  CONSTRAINT FACULTY_ENR_CHECK_SEM CHECK (SEM BETWEEN 1 AND 8) ENABLE,
  CONSTRAINT FACULTY_ENR_FOREIGN_FID FOREIGN KEY (FID) REFERENCES FACULTY_LIST (FID) ENABLE
);

CREATE TABLE STUDENT_CLASSENR(
  USN VARCHAR2(10),
  ENO NUMBER,
  CONSTRAINT STUDENT_CLASSENR_PRIME PRIMARY KEY (USN,ENO) ENABLE,
  CONSTRAINT STUDENT_CLASSENR_FOREIGN_USN FOREIGN KEY (USN) REFERENCES STUDENT_LIST (USN) ENABLE,
  CONSTRAINT STUDENT_CLASSENR_FOREIGN_ENO FOREIGN KEY (ENO) REFERENCES FACULTY_ENR (ENO) ENABLE
);

CREATE TABLE STUDENT_ATT(
  USN VARCHAR2(10),
  ENO NUMBER,
  DTE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT STUDENT_ATT_PRIME PRIMARY KEY (USN,ENO,DTE) ENABLE,
  CONSTRAINT STUDENT_ATT_FOREIGN_USN FOREIGN KEY (USN) REFERENCES STUDENT_LIST (USN) ENABLE,
  CONSTRAINT STUDENT_ATT_FOREIGN_ENO FOREIGN KEY (ENO) REFERENCES FACULTY_ENR (ENO) ENABLE
);

spool off;
