DROP TABLE ATT CASCADE CONSTRAINT;
DROP TABLE FAC_ENR CASCADE CONSTRAINT;
DROP TABLE WRITE_TEST CASCADE CONSTRAINT;
DROP TABLE TEST_SUB CASCADE CONSTRAINT;
DROP TABLE TEST_TME CASCADE CONSTRAINT;
DROP TABLE STUDENT_SUB_ENR CASCADE CONSTRAINT;
DROP TABLE STUDENT_SEM_ENR CASCADE CONSTRAINT;
DROP TABLE STUDENT_LIST CASCADE CONSTRAINT;
DROP TABLE CLASS_TCHR CASCADE CONSTRAINT;
DROP TABLE FACULTY_LIST CASCADE CONSTRAINT;
DROP TABLE CAMS_LOGIN CASCADE CONSTRAINT;


CREATE TABLE CAMS_LOGIN(
  USERID VARCHAR2(10),
  PASSWORD VARCHAR2(10),
  CONSTRAINT CAMS_LOGIN_PRIME PRIMARY KEY (USERID) ENABLE
);

CREATE TABLE FACULTY_LIST(
  FID VARCHAR2(7),
  NAME VARCHAR2(30) NOT NULL,
  DESIGNATION VARCHAR2(30) NOT NULL,
  BRANCH VARCHAR2(2),
  CONSTRAINT FACULTY_LIST_PRIME PRIMARY KEY (FID),
  CONSTRAINT FACULTY_LIST_FOREIGN FOREIGN KEY (FID) REFERENCES CAMS_LOGIN (USERID) ENABLE
);

CREATE TABLE CLASS_TCHR(
  SFID NUMBER,
  FID VARCHAR2(7),
  SECTION VARCHAR2(1) NOT NULL,
  SEM NUMBER,
  YEAR NUMBER,
  CONSTRAINT CLASS_TCHR_PRIME PRIMARY KEY (SFID) ENABLE,
  CONSTRAINT CLASS_TCHR_CHECK_SEM CHECK (SEM BETWEEN 1 AND 8) ENABLE,
  CONSTRAINT CLASS_TCHR_FOREIGN_FID FOREIGN KEY (FID) REFERENCES FACULTY_LIST (FID) ENABLE,
  CONSTRAINT CLASS_TCHR_UNIQUE UNIQUE (FID,SEM,YEAR) ENABLE
);

CREATE TABLE STUDENT_LIST(
  USN VARCHAR2(10),
  SNAME VARCHAR2(30),
  SEM NUMBER CONSTRAINT STUDENT_CHECK CHECK (SEM BETWEEN 1 AND 8) ENABLE,
  BRANCH VARCHAR(4),
  YEAR_OF_JOINING DATE,
  ADDRESS VARCHAR2(300),
  PARENT_PHNO NUMBER(15),
  PHNO NUMBER(15),
  PASSWORD VARCHAR2(20),
  CONSTRAINT STUDENT_LIST_PRIME PRIMARY KEY (USN) ENABLE,
  CONSTRAINT STUDENT_LIST_FOREIGN FOREIGN KEY (USN) REFERENCES CAMS_LOGIN (USERID) ENABLE
);

CREATE TABLE STUDENT_SEM_ENR(
  SUR2 NUMBER,
  USN VARCHAR2(10),
  BRANCH VARCHAR2(2),
  SEM NUMBER CONSTRAINT STUDENT_SEM_ENR_CHK CHECK(SEM BETWEEN 1 AND 8) ENABLE,
  BATCH NUMBER,
  SECTION VARCHAR2(1),
  YEAR NUMBER,
  CONSTRAINT STUDENT_SEM_ENR_PRIME PRIMARY KEY(SUR2) ENABLE,
  CONSTRAINT STUDENT_SEM_ENR_FOREIGN_USN FOREIGN KEY (USN) REFERENCES STUDENT_LIST(USN) ENABLE,
  CONSTRAINT STUDENT_SEM_ENR_UNIQUE UNIQUE (USN,SEM,SECTION,YEAR) ENABLE
);

CREATE TABLE STUDENT_SUB_ENR(
  SUR3 NUMBER,
  SCODE VARCHAR2(8),
  SNAME VARCHAR2(50),
  BRANCH VARCHAR2(2),
  CONSTRAINT STUDENT_SUB_ENR_PRIME PRIMARY KEY(SUR3) ENABLE,
  CONSTRAINT STUDENT_SUB_ENR_UNIQUE UNIQUE(SCODE,BRANCH) ENABLE
);

CREATE TABLE TEST_TME(
  SUR4 NUMBER,
  TNO NUMBER CONSTRAINT TEST_TME_CHK_TNO CHECK (TNO BETWEEN 1 AND 3) ENABLE,
  DTE DATE,
  SLOT VARCHAR2(1) CONSTRAINT TEST_TME_CHK_SLOT CHECK (SLOT='A' OR SLOT='M') ENABLE,
  CONSTRAINT TEST_TME_PRIME PRIMARY KEY (SUR4) ENABLE,
  CONSTRAINT TEST_TME_UNIQUE UNIQUE (TNO,DTE,SLOT) ENABLE
  );

CREATE TABLE TEST_SUB(
  SUR5 NUMBER,
  TNO NUMBER CONSTRAINT TEST_SUB_CHK_TNO CHECK (TNO BETWEEN 1 AND 3) ENABLE,
  SCODE VARCHAR2(8),
  CONSTRAINT TEST_SUB_PRIME PRIMARY KEY(SUR5) ENABLE,
  CONSTRAINT TEST_SUB_UNIQUE UNIQUE(TNO,SCODE) ENABLE
);

CREATE TABLE WRITE_TEST(
  SUR6 NUMBER,
  USN VARCHAR(10),
  SURT NUMBER,
  SCORE NUMBER,
  CONSTRAINT WRITE_TEST_PRIME PRIMARY KEY(SUR6) ENABLE,
  CONSTRAINT WRITE_TEST_FOREIGN_SURT FOREIGN KEY(SURT) REFERENCES TEST_SUB(SUR5) ENABLE,
  CONSTRAINT WRITE_TEST_UNIQUE UNIQUE(USN,SCORE) ENABLE,
  CONSTRAINT WRITE_TEST_FOREIGN_USN FOREIGN KEY(USN) REFERENCES STUDENT_LIST(USN) ENABLE
);

CREATE TABLE FAC_ENR(
  SUR7 NUMBER,
  FID VARCHAR2(7),
  SLOT VARCHAR2(1) CONSTRAINT FAC_ENR_CHK_SLOT CHECK (SLOT BETWEEN 1 AND 7) ENABLE,
  DAY VARCHAR2(3),
  SECTION VARCHAR2(1) NOT NULL,
  BRANCH VARCHAR2(2),
  YEAR NUMBER,
  SCODE VARCHAR2(8),
  CONSTRAINT FAC_ENR_UNIQUE UNIQUE(FID,SLOT,DAY,YEAR) ENABLE
);

CREATE TABLE ATT(
  SUR8 NUMBER,
  USN VARCHAR2(10),
  YEAR DATE,
  SLOT VARCHAR2(1) CONSTRAINT ATT_CHK_SLOT CHECK (SLOT BETWEEN 1 AND 7) ENABLE,
  SCODE VARCHAR2(8),
  DAY VARCHAR2(3),
  CONSTRAINT ATT_UNIQUE UNIQUE(USN,YEAR,SLOT) ENABLE,
  CONSTRAINT ATT_FOREIGN_USN FOREIGN KEY(USN) REFERENCES STUDENT_LIST(USN) ENABLE
);
