# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20170202_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptSubEnr',
            fields=[
                ('ssnor', models.FloatField(primary_key=True, serialize=False)),
                ('scode', models.CharField(blank=True, max_length=8, null=True)),
                ('sname', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'dept_sub_enr',
                'managed': False,
            },
        ),
    ]
