LOAD DATA INFILE 'CAMS_LOGIN.csv'
INTO TABLE CAMS_LOGIN
APPEND FIELDS TERMINATED BY ','
(USERID,PASSWORD)

LOAD DATA INFILE 'FACULTY_LIST.csv'
INTO TABLE FACULTY_LIST
APPEND FIELDS TERMINATED BY ','
(FID,NAME,DESIGNATION,BRANCH)
